name: Publish to npm

on:
  push:
    branches:
      - main # Change if your branch is different

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"
          npm version patch -m "Auto-bump version [skip ci]"
          git push origin main --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
